import { Injectable, signal } from '@angular/core';
import { StorageService } from './storage.service';

export type AppLanguage = 'en' | 'ar';

const LANGUAGE_KEY = 'gnouby_language';

const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  en: {
    brandName: 'Gnouby',
    brandTagline: 'PERFUMES',
    home: 'Home',
    perfumes: 'Perfumes',
    wishlist: 'Wishlist',
    cart: 'Cart',
    admin: 'Admin',
    dashboard: 'Dashboard',
    account: 'Account',
    settings: 'Settings',
    orders: 'Orders',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    browse: 'Browse',
    loading: 'Loading...',
    refresh: 'Refresh',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    yes: 'Yes',
    no: 'No',
    previous: 'Previous',
    next: 'Next',
    backHome: 'Back home',
    goToLogin: 'Go to login',
    loginRequired: 'Login required',
    adminsOnly: 'Admins only',
    notifications: 'Notifications',
    messages: 'Messages',
    noNotifications: 'No notifications yet',
    markAllRead: 'Mark all read',
    notificationTest: 'Test',
    live: 'Live',
    offline: 'Offline',
    switchToArabic: 'Switch to Arabic',
    switchToEnglish: 'Switch to English',
    toggleDarkMode: 'Toggle dark mode',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    closeFilters: 'Close filters',
    profile: 'Profile',
    password: 'Password',
    preferences: 'Preferences',
    preferencesHint: 'Theme, notifications, language, and privacy.',
    chatbot: 'Chatbot',
    dangerZone: 'Danger Zone',
    accountCenter: 'Account Center',
    settingsSubtitle: 'Manage your profile, preferences, privacy, and admin tools.',
    profileInformation: 'Profile Information',
    updatePublicDetails: 'Update your public account details.',
    fullName: 'Full name',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    saveProfile: 'Save profile',
    passwordSecurity: 'Password & Security',
    changeLocalPassword: 'Change your local test account password.',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm password',
    confirmNewPassword: 'Confirm new password',
    updatePassword: 'Update password',
    darkMode: 'Dark mode',
    darkModeHint: 'Switch between light and dark display.',
    emailNotifications: 'Email notifications',
    emailNotificationsHint: 'Receive account and activity updates.',
    orderUpdates: 'Order updates',
    orderUpdatesHint: 'Get notified when order status changes.',
    promotions: 'Promotions',
    promotionsHint: 'Receive offers and product drops.',
    language: 'Language',
    english: 'English',
    arabic: 'Arabic',
    profilePrivacy: 'Profile privacy',
    private: 'Private',
    membersOnly: 'Members only',
    savePreferences: 'Save preferences',
    chatbotSettings: 'Chatbot Settings',
    chatbotSettingsHint: 'Control assistant memory and tone for this account.',
    saveChatHistory: 'Save chat history',
    saveChatHistoryHint: 'Keep chatbot history separated per account.',
    assistantTone: 'Assistant tone',
    friendly: 'Friendly',
    direct: 'Direct',
    luxuryAdvisor: 'Luxury advisor',
    saveChatbotSettings: 'Save chatbot settings',
    clearChatHistory: 'Clear my chat history',
    adminSettings: 'Admin Settings',
    adminSettingsHint: 'Store and product management shortcuts.',
    manageProducts: 'Manage products',
    viewStorefront: 'View storefront',
    deleteAccountHint: 'Delete this local test account from the browser.',
    typeDelete: 'Type DELETE to confirm',
    deleteAccount: 'Delete account',
    loginToManageSettings: 'Login to manage your settings.',
    homeHeroTitleA: 'Discover the Essence of',
    homeHeroTitleB: 'Nubian Heritage',
    homeHeroSubtitle: 'Luxury fragrances inspired by the golden sands, ancient temples, and timeless beauty of Nubia',
    exploreCollection: 'Explore Collection',
    viewFeatured: 'View Featured',
    featuredCollections: 'Featured Collections',
    featuredSubtitle: 'Handpicked fragrances that embody the spirit of Nubia',
    nubianLegacy: 'The Nubian Legacy',
    legacyParagraphA: 'Our fragrances celebrate the warmth, beauty, and story of Nubian culture through carefully selected notes.',
    legacyParagraphB: 'Each bottle is crafted to feel luxurious, memorable, and deeply personal.',
    legacyPointA: 'Premium ingredients sourced from across Africa',
    legacyPointB: 'Traditional craftsmanship meets modern luxury',
    legacyPointC: 'Sustainable and ethical production',
    discoverStory: 'Discover Our Story',
    joinFamily: 'Join the Gnouby Family',
    newsletterSubtitle: 'Subscribe for exclusive offers and new fragrance announcements',
    enterEmail: 'Enter your email',
    subscribe: 'Subscribe',
    newsletterThanks: 'Thank you for subscribing with: {email}',
    filters: 'Filters',
    reset: 'Reset',
    sort: 'Sort',
    gender: 'Gender',
    rating: 'Rating',
    ratingOutOfFive: '{rating} out of 5',
    anyRating: 'Any rating',
    starsAndUp: '{rating}+ stars',
    price: 'Price',
    brands: 'Brands',
    showingFragrances: 'Showing {count} fragrance{plural}',
    showingFragrancesRange: 'Showing {from}-{to} of {total} fragrances',
    searchPerfumes: 'Search perfumes',
    searchPerfumesPlaceholder: 'Search by perfume, brand, note, or mood',
    searchPerfumesHint: 'Try a brand, note, category, or fragrance name.',
    searchResultsFor: '{count} result(s) for "{query}"',
    clearSearch: 'Clear search',
    defaultSort: 'Default',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    topRated: 'Top Rated',
    name: 'Name',
    noResults: 'No results',
    relaxFilters: 'Try relaxing your filters.',
    men: 'Men',
    women: 'Women',
    unisex: 'Unisex',
    add: 'Add',
    addToCart: 'Add to Cart',
    addToWishlist: 'Add to Wishlist',
    addedToCart: 'Added to cart!',
    addedToWishlist: 'Added to wishlist!',
    invalidPromo: 'Invalid promo code. Try NUBIAN10 or WELCOME15',
    promoApplied: '{code} applied! {discount}% off',
    viewPerfume: 'View perfume',
    concentration: 'Concentration',
    category: 'Category',
    season: 'Season',
    notes: 'Notes',
    relatedPerfumes: 'Related Perfumes',
    perfumeNotFound: 'Perfume not found',
    backToCollection: 'Back to collection',
    shoppingCart: 'Shopping Cart',
    cartEmpty: 'Your cart is empty',
    noSavedPerfumes: 'No saved perfumes yet',
    summary: 'Summary',
    subtotal: 'Subtotal',
    discount: 'Discount',
    total: 'Total',
    apply: 'Apply',
    create: 'Create',
    promoCode: 'Promo code',
    removePromo: 'Remove Promo',
    removeItem: 'Remove item',
    checkout: 'Checkout',
    checkoutTitle: 'Checkout',
    shippingDetails: 'Shipping Details',
    city: 'City',
    postalCode: 'Postal Code',
    paymentMethod: 'Payment Method',
    cashOnDelivery: 'Cash on delivery',
    orderSummary: 'Order Summary',
    qty: 'Qty',
    placeOrder: 'Place Order',
    processing: 'Processing...',
    shippingValidationError: 'Please complete all shipping fields with valid values.',
    orderPlacedSuccess: 'Order placed successfully! Thank you for shopping with Gnouby Perfumes.',
    searchOrders: 'Search orders',
    newest: 'Newest',
    oldest: 'Oldest',
    highestTotal: 'Highest total',
    lowestTotal: 'Lowest total',
    noOrdersFound: 'No orders found',
    startShopping: 'Start Shopping',
    reorder: 'Reorder',
    itemsAddedToCart: 'Items added to cart!',
    orderCount: '{count} order{plural}',
    itemCount: '{count} item(s)',
    status_all: 'All',
    status_processing: 'Processing',
    status_packed: 'Packed',
    status_shipped: 'Shipped',
    status_outfordelivery: 'Out for delivery',
    status_delivered: 'Delivered',
    status_cancelled: 'Cancelled',
    status: 'Status',
    updateStatus: 'Update Status',
    wallet: 'Wallet',
    cash: 'Cash',
    pending: 'pending',
    noOrdersYet: 'No orders yet',
    orderNumber: 'Order #{id}',
    premiumMember: 'Premium Member',
    tier: 'Tier',
    gold: 'Gold',
    manageYourInfo: 'Manage your info',
    editProfile: 'Edit Profile',
    viewHistory: 'View history',
    viewOrders: 'View Orders',
    viewWishlist: 'View Wishlist',
    myCart: 'My Cart',
    recentActivityEmpty: 'No recent activity to display',
    pleaseLogin: 'Please Log In',
    loginToViewAccount: 'You need to be logged in to view your account.',
    nameEmailRequired: 'Name and a valid email are required.',
    currentPasswordIncorrect: 'Current password is incorrect.',
    newPasswordsInvalid: 'New passwords must match and be at least 8 characters.',
    profileUpdatedSuccess: 'Profile updated successfully!',
    profileSettingsSaved: 'Profile settings saved.',
    newPasswordInvalid: 'New password must be at least 8 characters and match confirmation.',
    passwordUpdated: 'Password updated.',
    preferencesSaved: 'Preferences saved.',
    chatHistoryCleared: 'Chat history cleared.',
    typeDeleteToConfirm: 'Type DELETE to confirm account deletion.',
    accountDeleted: 'Account deleted.',
    welcomeBack: 'Welcome Back',
    loginSubtitle: 'Sign in to continue your fragrance journey',
    rememberMe: 'Remember me',
    or: 'or',
    createAccount: 'Create Account',
    joinGnoubyFamily: 'Join the Gnouby family',
    termsAgreement: 'I agree to the terms and privacy policy',
    createAnAccount: 'Create an account',
    newToGnouby: 'New to Gnouby?',
    alreadyRegistered: 'Already registered?',
    togglePassword: 'Toggle password',
    validEmailError: 'Please enter a valid email address',
    passwordMinSixError: 'Password must be at least 6 characters',
    invalidEmailOrPassword: 'Invalid email or password',
    fullNameRequired: 'Please enter your full name',
    passwordComplexityError: 'Password must contain uppercase, lowercase, number, and special character',
    passwordsMismatch: 'Passwords do not match',
    termsRequired: 'You must agree to the terms',
    activationEmailSent: 'Account created. Please check your email to activate it.',
    accountActivated: 'Your account is activated. You can login now.',
    accountActivationFailed: 'Activation link is invalid or expired.',
    forgotPassword: 'Forgot Password',
    forgotSubtitle: 'Enter your email to start recovery.',
    passwordResetPrepared: 'Password reset instructions prepared for {email}.',
    passwordResetFailed: 'Could not prepare password reset. Please try again.',
    sendInstructions: 'Send Instructions',
    continueToResetPassword: 'Continue to reset password',
    backToLogin: 'Back to login',
    resetPassword: 'Reset Password',
    resetSubtitle: 'Choose a new password.',
    resetPasswordValidation: 'Password must be at least 8 characters and both fields must match.',
    resetPasswordReady: 'Password reset flow is ready for backend confirmation.',
    resetPasswordFailed: 'Password reset failed. The link may be invalid or expired.',
    resetTokenMissing: 'Password reset link is missing or invalid.',
    resendConfirmation: 'Resend Confirmation',
    resendSubtitle: 'Request another confirmation email.',
    confirmationPrepared: 'Confirmation email prepared for {email}.',
    resend: 'Resend',
    verifyOtp: 'Verify OTP',
    otpSubtitle: 'Enter the code sent to your email.',
    verificationCode: 'Verification code',
    otpVerified: 'OTP verified locally.',
    otpInvalid: 'Enter a valid OTP code.',
    verify: 'Verify',
    resendCode: 'Resend code',
    googleCallback: 'Google Callback',
    googleCallbackSubtitle: 'This route is ready to receive OAuth callback data from your backend.',
    googleCallbackSigningIn: 'Finishing Google sign-in...',
    googleCallbackInvalid: 'Google sign-in response was invalid. Please try again.',
    signingGoogle: 'Signing you in with Google...',
    googleLoadFailed: 'Could not load Google sign-in. Please try again.',
    googleClientIdMissing: 'Add your Google Client ID first to enable Google login.',
    googleLoadingHint: 'Google login is loading. If the button does not appear, refresh the page.',
    googleCredentialMissing: 'Google did not return a login credential.',
    googleLoginSuccess: 'Signed in with Google successfully.',
    googleLoginFailed: 'Google login failed. Check the backend Client ID setting.',
    addGoogleClientId: 'Add Google Client ID',
    continueWithGoogle: 'Continue with Google',
    signUpWithGoogle: 'Sign up with Google',
    googleButtonUnavailable: 'Google button could not load. Add this site origin in Google Console and refresh.',
    googleButtonUnavailableShort: 'Google button did not load',
    googleButtonLoading: 'Loading Google sign-in...',
    tenantOnboarding: 'Tenant Onboarding',
    ownerOnboarding: 'Owner Onboarding',
    onboardingSubtitle: 'A ready route for setup steps when the backend role flow is added.',
    goToAccount: 'Go to Account',
    adminLoginRequired: 'Admin login required',
    loginFirstManageProducts: 'Login first to manage products.',
    adminsOnlyHint: 'This page is only available for admin accounts.',
    adminDashboard: 'Admin Dashboard',
    openAdminSidebar: 'Open admin sidebar',
    closeAdminSidebar: 'Close admin sidebar',
    wallets: 'Wallets',
    promoCodes: 'Promo Codes',
    supportInbox: 'Support Inbox',
    loadingOrders: 'Loading orders...',
    fetchingLatestOrders: 'Fetching the latest orders from the database.',
    ordersUnavailable: 'Orders unavailable',
    ordersLoadFailed: 'Could not load orders from the database. Check the API connection and admin login.',
    ordersRefreshFailed: 'Could not refresh orders.',
    orderStatusUpdateFailed: 'Could not update order status.',
    systemOverview: 'System overview',
    adminDashboardSubtitle: 'Live sales, orders, customers, wallets, and support activity.',
    loadingDashboard: 'Loading dashboard...',
    fetchingLiveData: 'Fetching live data from the database.',
    dashboardUnavailable: 'Dashboard unavailable',
    tryAgain: 'Try again',
    metricRevenue: 'Revenue',
    metricOrders: 'Orders',
    metricCustomers: 'Customers',
    metricWalletBalance: 'Wallet balance',
    metricProducts: 'Products',
    metricOpenSupport: 'Open support',
    operations: 'Operations',
    recentOrders: 'Recent Orders',
    manageAll: 'Manage all',
    finance: 'Finance',
    userWallets: 'User Wallets',
    walletsShown: '{count} shown',
    amount: 'Amount',
    credit: 'Credit',
    debit: 'Debit',
    reason: 'Reason',
    noWalletsYet: 'No wallets yet.',
    walletUpdated: 'Wallet updated.',
    walletUpdateFailed: 'Could not update wallet.',
    backendNotReachable: 'Backend is not reachable. Start Perfiumes.Api from Visual Studio, then try again.',
    adminDashboardLoadFailed: 'Could not load admin dashboard. Please refresh or login again as admin.',
    adminAdjustment: 'Admin adjustment',
    walletsSubtitle: 'Review customer balances and apply wallet adjustments.',
    totalBalance: 'Total balance',
    lifetimeCredit: 'Lifetime credit',
    lifetimeDebit: 'Lifetime debit',
    customers: 'Customers',
    walletManagement: 'Wallet management',
    searchWallets: 'Search wallets',
    loadingWallets: 'Loading wallets...',
    fetchingWalletData: 'Fetching live wallet data.',
    walletsUnavailable: 'Wallets unavailable',
    walletsLoadFailed: 'Could not load wallets from the database. Check the API connection and admin login.',
    balance: 'Balance',
    updated: 'Updated',
    noWalletsFound: 'No wallets found',
    tryDifferentSearch: 'Try a different search term.',
    marketing: 'Marketing',
    promosSubtitle: 'Create limited-time discounts and notify customers instantly.',
    newPromoCode: 'New promo code',
    code: 'Code',
    discountPercent: 'Discount percent',
    expiresAt: 'Expires at',
    creating: 'Creating...',
    createPromo: 'Create promo',
    existing: 'Existing',
    totalCount: '{count} total',
    loadingPromos: 'Loading promos...',
    promosUnavailable: 'Promos unavailable',
    promosLoadFailed: 'Could not load promo codes.',
    promoValidationError: 'Enter a valid promo code, discount, and expiration date.',
    promoCreated: 'Promo code created and customers were notified.',
    promoCreateFailed: 'Could not create promo code.',
    percentOffExpires: '{discount}% off · expires {date}',
    createdBy: 'Created by {email}',
    expired: 'Expired',
    active: 'Active',
    noPromoCodesYet: 'No promo codes yet',
    loginFirstSupportMessages: 'Please login first to manage support messages.',
    supportInboxAdminsOnly: 'This inbox is only available for admin accounts.',
    conversationCount: '{count} conversations',
    refreshMessages: 'Refresh messages',
    refreshing: 'Refreshing',
    conversations: 'Conversations',
    noMessages: 'No messages',
    newConversationsHint: 'New conversations will show here.',
    close: 'Close',
    gnoubySupport: 'Gnouby Support',
    replyTo: 'Reply to {name}',
    sendReply: 'Send reply',
    loadingMessages: 'Loading messages',
    inboxOpeningNow: 'The inbox is opening now.',
    messagesUnavailable: 'Messages unavailable',
    selectConversation: 'Select a conversation',
    chooseCustomerToReply: 'Choose a customer from the left to reply.',
    supportMessagesLoadFailed: 'Could not load support messages.',
    replyFailed: 'Reply failed.',
    conversationCloseFailed: 'Could not close conversation.',
    conversationStatus_open: 'Open',
    conversationStatus_answered: 'Answered',
    conversationStatus_closed: 'Closed',
    manageProductsTitle: 'Manage Products',
    manageProductsSubtitle: 'Add, edit, and remove seeded backend products.',
    cancelEdit: 'Cancel edit',
    product: 'Product',
    stock: 'Stock',
    featured: 'Featured',
    imageUrl: 'Image URL',
    description: 'Description',
    notesComma: 'Notes comma separated',
    seasonComma: 'Season comma separated',
    featuredProduct: 'Featured product',
    products: 'Products',
    productsLoaded: 'Showing {from}-{to} of {total} products from backend',
    loadingProducts: 'Loading products...',
    saveProduct: 'Save product',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    updateProduct: 'Update product',
    saving: 'Saving...',
    brand: 'Brand',
    productRequiredFields: 'Please fill name, brand, and category.',
    productUpdated: 'Product updated.',
    productAdded: 'Product added.',
    productSaveFailed: 'Could not save product. Check backend/admin token.',
    confirmDeleteProduct: 'Delete {name}?',
    productDeleted: 'Product deleted.',
    productDeleteFailed: 'Could not delete product.',
    loginAgainAdmin: 'Please login again as admin.',
    adminApiLoginFailed: 'Admin API login failed. Please login again.',
    gnoubyAssistant: 'Gnouby Assistant',
    perfumeChatbot: 'Perfume Chatbot',
    newChat: 'New',
    startNewChat: 'Start new chat',
    closeChatbot: 'Close chatbot',
    askFragrance: 'Ask for a fragrance...',
    sendMessage: 'Send message',
    chatbotWelcome: 'Hi! I am Gnouby Assistant. Tell me what you want: woody, fresh, sweet, oriental, men/women, or your budget.',
    chatbotBackendError: 'Could not reach the backend right now. Make sure the .NET 10 API is running on localhost:5156.',
    footerAbout: 'Luxury fragrances inspired by Nubian heritage and timeless elegance.',
    quickLinks: 'Quick Links',
    customerService: 'Customer Service',
    contactUs: 'Contact Us',
    shippingInfo: 'Shipping Info',
    returns: 'Returns',
    followUs: 'Follow Us'
  },
  ar: {
    brandName: 'جنوبي',
    brandTagline: 'عطور',
    home: 'الرئيسية',
    perfumes: 'العطور',
    wishlist: 'المفضلة',
    cart: 'السلة',
    admin: 'الإدارة',
    dashboard: 'لوحة التحكم',
    account: 'الحساب',
    settings: 'الإعدادات',
    orders: 'الطلبات',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    logout: 'تسجيل الخروج',
    browse: 'تصفح',
    loading: 'جارِ التحميل...',
    refresh: 'تحديث',
    cancel: 'إلغاء',
    save: 'حفظ',
    edit: 'تعديل',
    delete: 'حذف',
    yes: 'نعم',
    no: 'لا',
    previous: 'السابق',
    next: 'التالي',
    backHome: 'العودة للرئيسية',
    goToLogin: 'اذهب لتسجيل الدخول',
    loginRequired: 'تسجيل الدخول مطلوب',
    adminsOnly: 'للإدارة فقط',
    notifications: 'الإشعارات',
    messages: 'الرسائل',
    noNotifications: 'لا توجد إشعارات بعد',
    markAllRead: 'تحديد الكل كمقروء',
    notificationTest: 'تجربة',
    live: 'مباشر',
    offline: 'غير متصل',
    switchToArabic: 'التبديل إلى العربية',
    switchToEnglish: 'التبديل إلى الإنجليزية',
    toggleDarkMode: 'تبديل الوضع الداكن',
    openMenu: 'فتح القائمة',
    closeMenu: 'إغلاق القائمة',
    closeFilters: 'إغلاق الفلاتر',
    profile: 'الملف الشخصي',
    password: 'كلمة المرور',
    preferences: 'التفضيلات',
    preferencesHint: 'المظهر والإشعارات واللغة والخصوصية.',
    chatbot: 'المساعد',
    dangerZone: 'منطقة الخطر',
    accountCenter: 'مركز الحساب',
    settingsSubtitle: 'تحكم في بياناتك وتفضيلاتك وخصوصيتك وأدوات الإدارة.',
    profileInformation: 'بيانات الحساب',
    updatePublicDetails: 'حدّث بيانات حسابك الأساسية.',
    fullName: 'الاسم بالكامل',
    email: 'البريد الإلكتروني',
    phone: 'رقم الهاتف',
    address: 'العنوان',
    saveProfile: 'حفظ البيانات',
    passwordSecurity: 'كلمة المرور والأمان',
    changeLocalPassword: 'غيّر كلمة مرور حساب الاختبار المحلي.',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    confirmPassword: 'تأكيد كلمة المرور',
    confirmNewPassword: 'تأكيد كلمة المرور الجديدة',
    updatePassword: 'تحديث كلمة المرور',
    darkMode: 'الوضع الداكن',
    darkModeHint: 'بدّل بين المظهر الفاتح والداكن.',
    emailNotifications: 'إشعارات البريد',
    emailNotificationsHint: 'استقبل تحديثات الحساب والنشاط.',
    orderUpdates: 'تحديثات الطلبات',
    orderUpdatesHint: 'اعرف عند تغيّر حالة الطلب.',
    promotions: 'العروض',
    promotionsHint: 'استقبل العروض والمنتجات الجديدة.',
    language: 'اللغة',
    english: 'الإنجليزية',
    arabic: 'العربية',
    profilePrivacy: 'خصوصية الحساب',
    private: 'خاص',
    membersOnly: 'للأعضاء فقط',
    savePreferences: 'حفظ التفضيلات',
    chatbotSettings: 'إعدادات المساعد',
    chatbotSettingsHint: 'تحكم في ذاكرة ونبرة المساعد لهذا الحساب.',
    saveChatHistory: 'حفظ سجل الشات',
    saveChatHistoryHint: 'احتفظ بسجل منفصل لكل حساب.',
    assistantTone: 'نبرة المساعد',
    friendly: 'ودود',
    direct: 'مباشر',
    luxuryAdvisor: 'مستشار فاخر',
    saveChatbotSettings: 'حفظ إعدادات المساعد',
    clearChatHistory: 'مسح سجل الشات',
    adminSettings: 'إعدادات الإدارة',
    adminSettingsHint: 'اختصارات إدارة المتجر والمنتجات.',
    manageProducts: 'إدارة المنتجات',
    viewStorefront: 'عرض المتجر',
    deleteAccountHint: 'حذف حساب الاختبار المحلي من المتصفح.',
    typeDelete: 'اكتب DELETE للتأكيد',
    deleteAccount: 'حذف الحساب',
    loginToManageSettings: 'سجل الدخول لإدارة الإعدادات.',
    homeHeroTitleA: 'اكتشف عبير',
    homeHeroTitleB: 'التراث النوبي',
    homeHeroSubtitle: 'عطور فاخرة مستوحاة من الرمال الذهبية والمعابد القديمة وجمال النوبة الخالد',
    exploreCollection: 'استكشف المجموعة',
    viewFeatured: 'عرض المميز',
    featuredCollections: 'المجموعات المميزة',
    featuredSubtitle: 'عطور مختارة بعناية تحمل روح النوبة',
    nubianLegacy: 'الإرث النوبي',
    legacyParagraphA: 'عطورنا تحتفي بدفء وجمال وحكاية الثقافة النوبية من خلال نوتات مختارة بعناية.',
    legacyParagraphB: 'كل زجاجة مصممة لتمنحك إحساسًا فاخرًا ومميزًا وشخصيًا.',
    legacyPointA: 'مكونات فاخرة من أنحاء أفريقيا',
    legacyPointB: 'حِرفة تقليدية بروح عصرية فاخرة',
    legacyPointC: 'إنتاج مستدام وأخلاقي',
    discoverStory: 'اكتشف قصتنا',
    joinFamily: 'انضم لعائلة جنوبي',
    newsletterSubtitle: 'اشترك للحصول على عروض حصرية وإعلانات العطور الجديدة',
    enterEmail: 'اكتب بريدك الإلكتروني',
    subscribe: 'اشترك',
    newsletterThanks: 'شكرًا لاشتراكك بالبريد: {email}',
    filters: 'الفلاتر',
    reset: 'إعادة ضبط',
    sort: 'ترتيب',
    gender: 'النوع',
    rating: 'التقييم',
    ratingOutOfFive: '{rating} من 5',
    anyRating: 'أي تقييم',
    starsAndUp: '{rating}+ نجوم',
    price: 'السعر',
    brands: 'العلامات التجارية',
    showingFragrances: 'عرض {count} عطر',
    showingFragrancesRange: 'عرض {from}-{to} من {total} عطر',
    searchPerfumes: 'البحث في العطور',
    searchPerfumesPlaceholder: 'ابحث باسم العطر أو البراند أو النوتة أو الإحساس',
    searchPerfumesHint: 'جرّب براند أو نوتة أو تصنيف أو اسم عطر.',
    searchResultsFor: '{count} نتيجة عن "{query}"',
    clearSearch: 'مسح البحث',
    defaultSort: 'الافتراضي',
    priceLowHigh: 'السعر: من الأقل للأعلى',
    priceHighLow: 'السعر: من الأعلى للأقل',
    topRated: 'الأعلى تقييمًا',
    name: 'الاسم',
    noResults: 'لا توجد نتائج',
    relaxFilters: 'جرّب تخفيف الفلاتر.',
    men: 'رجالي',
    women: 'حريمي',
    unisex: 'للجنسين',
    add: 'إضافة',
    addToCart: 'إضافة للسلة',
    addToWishlist: 'إضافة للمفضلة',
    addedToCart: 'تمت الإضافة للسلة!',
    addedToWishlist: 'تمت الإضافة للمفضلة!',
    invalidPromo: 'كود الخصم غير صحيح. جرّب NUBIAN10 أو WELCOME15',
    promoApplied: 'تم تطبيق {code}! خصم {discount}%',
    viewPerfume: 'عرض العطر',
    concentration: 'التركيز',
    category: 'التصنيف',
    season: 'الموسم',
    notes: 'النوتات',
    relatedPerfumes: 'عطور مشابهة',
    perfumeNotFound: 'العطر غير موجود',
    backToCollection: 'العودة للمجموعة',
    shoppingCart: 'سلة التسوق',
    cartEmpty: 'السلة فارغة',
    noSavedPerfumes: 'لا توجد عطور محفوظة بعد',
    summary: 'الملخص',
    subtotal: 'الإجمالي الفرعي',
    discount: 'الخصم',
    total: 'الإجمالي',
    apply: 'تطبيق',
    create: 'إنشاء',
    promoCode: 'كود الخصم',
    removePromo: 'إزالة الخصم',
    removeItem: 'حذف المنتج',
    checkout: 'الدفع',
    checkoutTitle: 'الدفع',
    shippingDetails: 'بيانات الشحن',
    city: 'المدينة',
    postalCode: 'الرمز البريدي',
    paymentMethod: 'طريقة الدفع',
    cashOnDelivery: 'الدفع عند الاستلام',
    orderSummary: 'ملخص الطلب',
    qty: 'الكمية',
    placeOrder: 'تأكيد الطلب',
    processing: 'جارِ التنفيذ...',
    shippingValidationError: 'من فضلك أكمل كل بيانات الشحن بقيم صحيحة.',
    orderPlacedSuccess: 'تم تسجيل الطلب بنجاح! شكرًا لتسوقك من جنوبي للعطور.',
    searchOrders: 'ابحث في الطلبات',
    newest: 'الأحدث',
    oldest: 'الأقدم',
    highestTotal: 'أعلى إجمالي',
    lowestTotal: 'أقل إجمالي',
    noOrdersFound: 'لا توجد طلبات',
    startShopping: 'ابدأ التسوق',
    reorder: 'إعادة الطلب',
    itemsAddedToCart: 'تمت إضافة المنتجات للسلة!',
    orderCount: '{count} طلب',
    itemCount: '{count} منتج',
    status_all: 'الكل',
    status_processing: 'قيد التنفيذ',
    status_packed: 'تم التجهيز',
    status_shipped: 'تم الشحن',
    status_outfordelivery: 'في الطريق إليك',
    status_delivered: 'تم التسليم',
    status_cancelled: 'ملغي',
    status: 'الحالة',
    updateStatus: 'تحديث الحالة',
    wallet: 'المحفظة',
    cash: 'كاش',
    pending: 'قيد الانتظار',
    noOrdersYet: 'لا توجد طلبات بعد',
    orderNumber: 'طلب #{id}',
    premiumMember: 'عضو مميز',
    tier: 'الفئة',
    gold: 'ذهبي',
    manageYourInfo: 'إدارة بياناتك',
    editProfile: 'تعديل الملف',
    viewHistory: 'عرض السجل',
    viewOrders: 'عرض الطلبات',
    viewWishlist: 'عرض المفضلة',
    myCart: 'سلتي',
    recentActivityEmpty: 'لا يوجد نشاط حديث للعرض',
    pleaseLogin: 'برجاء تسجيل الدخول',
    loginToViewAccount: 'يجب تسجيل الدخول لعرض حسابك.',
    nameEmailRequired: 'الاسم والبريد الإلكتروني الصحيح مطلوبان.',
    currentPasswordIncorrect: 'كلمة المرور الحالية غير صحيحة.',
    newPasswordsInvalid: 'كلمات المرور الجديدة يجب أن تتطابق وألا تقل عن 8 أحرف.',
    profileUpdatedSuccess: 'تم تحديث الملف الشخصي بنجاح!',
    profileSettingsSaved: 'تم حفظ إعدادات الملف الشخصي.',
    newPasswordInvalid: 'كلمة المرور الجديدة يجب ألا تقل عن 8 أحرف وأن تطابق التأكيد.',
    passwordUpdated: 'تم تحديث كلمة المرور.',
    preferencesSaved: 'تم حفظ التفضيلات.',
    chatHistoryCleared: 'تم مسح سجل الشات.',
    typeDeleteToConfirm: 'اكتب DELETE لتأكيد حذف الحساب.',
    accountDeleted: 'تم حذف الحساب.',
    welcomeBack: 'مرحبًا بعودتك',
    loginSubtitle: 'سجل الدخول لتكمل رحلتك مع العطور',
    rememberMe: 'تذكرني',
    or: 'أو',
    createAccount: 'إنشاء حساب',
    joinGnoubyFamily: 'انضم لعائلة جنوبي',
    termsAgreement: 'أوافق على الشروط وسياسة الخصوصية',
    createAnAccount: 'إنشاء حساب',
    newToGnouby: 'جديد في جنوبي؟',
    alreadyRegistered: 'لديك حساب بالفعل؟',
    togglePassword: 'إظهار أو إخفاء كلمة المرور',
    validEmailError: 'من فضلك اكتب بريد إلكتروني صحيح',
    passwordMinSixError: 'كلمة المرور يجب ألا تقل عن 6 أحرف',
    invalidEmailOrPassword: 'البريد الإلكتروني أو كلمة المرور غير صحيح',
    fullNameRequired: 'من فضلك اكتب اسمك بالكامل',
    passwordComplexityError: 'كلمة المرور لازم تحتوي على حرف كبير وصغير ورقم ورمز خاص',
    passwordsMismatch: 'كلمتا المرور غير متطابقتين',
    termsRequired: 'يجب الموافقة على الشروط',
    activationEmailSent: 'تم إنشاء الحساب. راجع بريدك الإلكتروني لتفعيله.',
    accountActivated: 'تم تفعيل حسابك. يمكنك تسجيل الدخول الآن.',
    accountActivationFailed: 'رابط التفعيل غير صحيح أو منتهي الصلاحية.',
    forgotPassword: 'نسيت كلمة المرور',
    forgotSubtitle: 'اكتب بريدك الإلكتروني لبدء الاسترجاع.',
    passwordResetPrepared: 'تم تجهيز تعليمات استعادة كلمة المرور لـ {email}.',
    passwordResetFailed: 'تعذر تجهيز استعادة كلمة المرور. حاول مرة أخرى.',
    sendInstructions: 'إرسال التعليمات',
    continueToResetPassword: 'المتابعة لإعادة تعيين كلمة المرور',
    backToLogin: 'العودة لتسجيل الدخول',
    resetPassword: 'إعادة تعيين كلمة المرور',
    resetSubtitle: 'اختر كلمة مرور جديدة.',
    resetPasswordValidation: 'كلمة المرور يجب ألا تقل عن 8 أحرف ويجب أن يتطابق الحقلان.',
    resetPasswordReady: 'مسار إعادة تعيين كلمة المرور جاهز لتأكيد الباك اند.',
    resetPasswordFailed: 'فشل إعادة تعيين كلمة المرور. قد يكون الرابط غير صحيح أو منتهي الصلاحية.',
    resetTokenMissing: 'رابط إعادة تعيين كلمة المرور غير موجود أو غير صحيح.',
    resendConfirmation: 'إعادة إرسال التأكيد',
    resendSubtitle: 'اطلب رسالة تأكيد أخرى.',
    confirmationPrepared: 'تم تجهيز رسالة التأكيد لـ {email}.',
    resend: 'إرسال مرة أخرى',
    verifyOtp: 'تأكيد الكود',
    otpSubtitle: 'اكتب الكود المرسل إلى بريدك.',
    verificationCode: 'كود التحقق',
    otpVerified: 'تم تأكيد الكود محليًا.',
    otpInvalid: 'اكتب كود تحقق صحيح.',
    verify: 'تأكيد',
    resendCode: 'إعادة إرسال الكود',
    googleCallback: 'Google Callback',
    googleCallbackSubtitle: 'هذه الصفحة جاهزة لاستقبال بيانات OAuth من الباك اند.',
    googleCallbackSigningIn: 'جارِ إكمال تسجيل الدخول بواسطة Google...',
    googleCallbackInvalid: 'استجابة تسجيل Google غير صحيحة. حاول مرة أخرى.',
    signingGoogle: 'جارِ تسجيل الدخول بواسطة Google...',
    googleLoadFailed: 'تعذر تحميل تسجيل الدخول بواسطة Google. حاول مرة أخرى.',
    googleClientIdMissing: 'أضف Google Client ID أولًا لتفعيل تسجيل الدخول بواسطة Google.',
    googleLoadingHint: 'تسجيل Google جارِ التحميل. لو الزر لم يظهر، حدّث الصفحة.',
    googleCredentialMissing: 'Google لم يرجع بيانات تسجيل الدخول.',
    googleLoginSuccess: 'تم تسجيل الدخول بواسطة Google بنجاح.',
    googleLoginFailed: 'فشل تسجيل الدخول بواسطة Google. تحقق من Client ID في الباك اند.',
    addGoogleClientId: 'أضف Google Client ID',
    continueWithGoogle: 'المتابعة بواسطة Google',
    signUpWithGoogle: 'إنشاء حساب بواسطة Google',
    googleButtonUnavailable: 'تعذر تحميل زر Google. أضف رابط الموقع في Google Console ثم حدّث الصفحة.',
    googleButtonUnavailableShort: 'زر Google لم يتم تحميله',
    googleButtonLoading: 'جارِ تحميل تسجيل الدخول بواسطة Google...',
    tenantOnboarding: 'إعداد المستأجر',
    ownerOnboarding: 'إعداد المالك',
    onboardingSubtitle: 'صفحة جاهزة لخطوات الإعداد عند إضافة نظام الأدوار من الباك اند.',
    goToAccount: 'اذهب للحساب',
    adminLoginRequired: 'تسجيل دخول الإدارة مطلوب',
    loginFirstManageProducts: 'سجل الدخول أولًا لإدارة المنتجات.',
    adminsOnlyHint: 'هذه الصفحة متاحة لحسابات الإدارة فقط.',
    adminDashboard: 'لوحة الإدارة',
    openAdminSidebar: 'فتح قائمة الإدارة',
    closeAdminSidebar: 'إغلاق قائمة الإدارة',
    wallets: 'المحافظ',
    promoCodes: 'أكواد الخصم',
    supportInbox: 'صندوق الدعم',
    loadingOrders: 'جارِ تحميل الطلبات...',
    fetchingLatestOrders: 'جارِ جلب أحدث الطلبات من قاعدة البيانات.',
    ordersUnavailable: 'الطلبات غير متاحة',
    ordersLoadFailed: 'تعذر تحميل الطلبات من قاعدة البيانات. تحقق من اتصال الـ API وتسجيل دخول الأدمن.',
    ordersRefreshFailed: 'تعذر تحديث الطلبات.',
    orderStatusUpdateFailed: 'تعذر تحديث حالة الطلب.',
    systemOverview: 'نظرة عامة على النظام',
    adminDashboardSubtitle: 'المبيعات والطلبات والعملاء والمحافظ ورسائل الدعم مباشرة.',
    loadingDashboard: 'جارِ تحميل لوحة الإدارة...',
    fetchingLiveData: 'جارِ جلب البيانات المباشرة من قاعدة البيانات.',
    dashboardUnavailable: 'لوحة الإدارة غير متاحة',
    tryAgain: 'حاول مرة أخرى',
    metricRevenue: 'الإيرادات',
    metricOrders: 'الطلبات',
    metricCustomers: 'العملاء',
    metricWalletBalance: 'رصيد المحافظ',
    metricProducts: 'المنتجات',
    metricOpenSupport: 'رسائل الدعم المفتوحة',
    operations: 'العمليات',
    recentOrders: 'أحدث الطلبات',
    manageAll: 'إدارة الكل',
    finance: 'المالية',
    userWallets: 'محافظ المستخدمين',
    walletsShown: '{count} ظاهر',
    amount: 'المبلغ',
    credit: 'إضافة رصيد',
    debit: 'خصم رصيد',
    reason: 'السبب',
    noWalletsYet: 'لا توجد محافظ بعد.',
    walletUpdated: 'تم تحديث المحفظة.',
    walletUpdateFailed: 'تعذر تحديث المحفظة.',
    backendNotReachable: 'لا يمكن الوصول للباك اند. شغّل Perfiumes.Api من Visual Studio ثم حاول مرة أخرى.',
    adminDashboardLoadFailed: 'تعذر تحميل لوحة الإدارة. حدّث الصفحة أو سجل الدخول مرة أخرى كأدمن.',
    adminAdjustment: 'تعديل من الإدارة',
    walletsSubtitle: 'راجع أرصدة العملاء ونفّذ تعديلات المحافظ.',
    totalBalance: 'إجمالي الرصيد',
    lifetimeCredit: 'إجمالي الإضافات',
    lifetimeDebit: 'إجمالي الخصومات',
    customers: 'العملاء',
    walletManagement: 'إدارة المحافظ',
    searchWallets: 'ابحث في المحافظ',
    loadingWallets: 'جارِ تحميل المحافظ...',
    fetchingWalletData: 'جارِ جلب بيانات المحافظ المباشرة.',
    walletsUnavailable: 'المحافظ غير متاحة',
    walletsLoadFailed: 'تعذر تحميل المحافظ من قاعدة البيانات. تحقق من اتصال الـ API وتسجيل دخول الأدمن.',
    balance: 'الرصيد',
    updated: 'آخر تحديث',
    noWalletsFound: 'لا توجد محافظ',
    tryDifferentSearch: 'جرّب كلمة بحث مختلفة.',
    marketing: 'التسويق',
    promosSubtitle: 'أنشئ خصومات مؤقتة وأرسل إشعارًا للعملاء فورًا.',
    newPromoCode: 'كود خصم جديد',
    code: 'الكود',
    discountPercent: 'نسبة الخصم',
    expiresAt: 'ينتهي في',
    creating: 'جارِ الإنشاء...',
    createPromo: 'إنشاء كود خصم',
    existing: 'الحالي',
    totalCount: '{count} إجمالي',
    loadingPromos: 'جارِ تحميل أكواد الخصم...',
    promosUnavailable: 'أكواد الخصم غير متاحة',
    promosLoadFailed: 'تعذر تحميل أكواد الخصم.',
    promoValidationError: 'أدخل كود خصم ونسبة وتاريخ انتهاء صحيحين.',
    promoCreated: 'تم إنشاء كود الخصم وإشعار العملاء.',
    promoCreateFailed: 'تعذر إنشاء كود الخصم.',
    percentOffExpires: 'خصم {discount}% · ينتهي {date}',
    createdBy: 'أنشئ بواسطة {email}',
    expired: 'منتهي',
    active: 'نشط',
    noPromoCodesYet: 'لا توجد أكواد خصم بعد',
    loginFirstSupportMessages: 'سجل الدخول أولًا لإدارة رسائل الدعم.',
    supportInboxAdminsOnly: 'صندوق الدعم متاح لحسابات الإدارة فقط.',
    conversationCount: '{count} محادثة',
    refreshMessages: 'تحديث الرسائل',
    refreshing: 'جارِ التحديث',
    conversations: 'المحادثات',
    noMessages: 'لا توجد رسائل',
    newConversationsHint: 'المحادثات الجديدة ستظهر هنا.',
    close: 'إغلاق',
    gnoubySupport: 'دعم جنوبي',
    replyTo: 'رد على {name}',
    sendReply: 'إرسال الرد',
    loadingMessages: 'جارِ تحميل الرسائل',
    inboxOpeningNow: 'صندوق الرسائل يفتح الآن.',
    messagesUnavailable: 'الرسائل غير متاحة',
    selectConversation: 'اختر محادثة',
    chooseCustomerToReply: 'اختر عميلًا للرد عليه.',
    supportMessagesLoadFailed: 'تعذر تحميل رسائل الدعم.',
    replyFailed: 'فشل إرسال الرد.',
    conversationCloseFailed: 'تعذر إغلاق المحادثة.',
    conversationStatus_open: 'مفتوحة',
    conversationStatus_answered: 'تم الرد',
    conversationStatus_closed: 'مغلقة',
    manageProductsTitle: 'إدارة المنتجات',
    manageProductsSubtitle: 'أضف وعدّل واحذف منتجات الباك اند.',
    cancelEdit: 'إلغاء التعديل',
    product: 'المنتج',
    stock: 'المخزون',
    featured: 'مميز',
    imageUrl: 'رابط الصورة',
    description: 'الوصف',
    notesComma: 'النوتات مفصولة بفواصل',
    seasonComma: 'المواسم مفصولة بفواصل',
    featuredProduct: 'منتج مميز',
    products: 'المنتجات',
    productsLoaded: 'عرض {from}-{to} من {total} منتج من الباك اند',
    loadingProducts: 'جارِ تحميل المنتجات...',
    saveProduct: 'حفظ المنتج',
    addProduct: 'إضافة منتج',
    editProduct: 'تعديل منتج',
    updateProduct: 'تحديث المنتج',
    saving: 'جارِ الحفظ...',
    brand: 'العلامة التجارية',
    productRequiredFields: 'من فضلك املأ الاسم والعلامة التجارية والتصنيف.',
    productUpdated: 'تم تحديث المنتج.',
    productAdded: 'تمت إضافة المنتج.',
    productSaveFailed: 'تعذر حفظ المنتج. تحقق من الباك اند أو صلاحية الأدمن.',
    confirmDeleteProduct: 'حذف {name}؟',
    productDeleted: 'تم حذف المنتج.',
    productDeleteFailed: 'تعذر حذف المنتج.',
    loginAgainAdmin: 'من فضلك سجل الدخول مرة أخرى كأدمن.',
    adminApiLoginFailed: 'فشل تسجيل دخول Admin API. من فضلك سجل الدخول مرة أخرى.',
    gnoubyAssistant: 'مساعد جنوبي',
    perfumeChatbot: 'شات العطور',
    newChat: 'جديد',
    startNewChat: 'بدء شات جديد',
    closeChatbot: 'إغلاق الشات',
    askFragrance: 'اسأل عن عطر...',
    sendMessage: 'إرسال الرسالة',
    chatbotWelcome: 'أهلًا! أنا مساعد جنوبي. قلّي عايز إيه: خشبي، منعش، حلو، شرقي، رجالي/حريمي، أو الميزانية.',
    chatbotBackendError: 'مش قادر أوصل للباك اند حاليًا. تأكد إن .NET 10 API شغال على localhost:5156.',
    footerAbout: 'عطور فاخرة مستوحاة من التراث النوبي والأناقة الخالدة.',
    quickLinks: 'روابط سريعة',
    customerService: 'خدمة العملاء',
    contactUs: 'تواصل معنا',
    shippingInfo: 'معلومات الشحن',
    returns: 'الاسترجاع',
    followUs: 'تابعنا'
  }
};

@Injectable({ providedIn: 'root' })
export class LocalizationService {
  readonly language = signal<AppLanguage>(this.storage.get<AppLanguage>(LANGUAGE_KEY, 'en'));

  constructor(private readonly storage: StorageService) {
    this.applyDocumentLanguage(this.language());
  }

  setLanguage(language: AppLanguage): void {
    this.storage.set(LANGUAGE_KEY, language);
    this.language.set(language);
    this.applyDocumentLanguage(language);
  }

  t(key: string): string {
    const language = this.language();
    return TRANSLATIONS[language][key] || TRANSLATIONS.en[key] || key;
  }

  isRtl(): boolean {
    return this.language() === 'ar';
  }

  private applyDocumentLanguage(language: AppLanguage): void {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.body.dir = language === 'ar' ? 'rtl' : 'ltr';
  }
}
